# Generated by Django 5.2.5 on 2025-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_category_category_name"),
        ("vendor", "0003_alter_vendor_vendor_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("vendor", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="fooditem",
            unique_together={("vendor", "slug")},
        ),
    ]
